language: python

python:
  - "2.7"

sudo: required

services:
  - docker

env:
  - DOCKER_IMG=cpascual/taurus-test:debian-jessie SKIP_DOC=Y
  - DOCKER_IMG=cpascual/taurus-test:debian-stretch
  - DOCKER_IMG=cpascual/taurus-test:debian-buster

matrix:
    allow_failures:
        - env: DOCKER_IMG=cpascual/taurus-test:debian-buster

before_install:
  - docker run -d --name=taurus-test -h taurus-test --volume=`pwd`:/taurus $DOCKER_IMG
  - sleep 10
  
script:
  - docker exec taurus-test /bin/bash -c "cd /taurus ; python setup.py install"
  - travis_wait docker exec taurus-test /bin/bash -c "TAURUS_STARTER_WAIT=5 taurustestsuite -e 'taurus\.core\.util\.test\.test_timer'"
  - if [[ $SKIP_DOC != "Y" ]]; then docker exec taurus-test /bin/bash -c "cd /taurus ; python setup.py build_sphinx"; fi
  - if [[ $SKIP_DOC != "Y" ]]; then docker exec taurus-test /bin/bash -c "touch /taurus/build/sphinx/html/.nojekyll"; fi 
  
deploy:
  provider: pages
  local_dir: ./build/sphinx/html
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: develop
    condition: "$DOCKER_IMG = cpascual/taurus-test:debian-stretch"
